name: Basic Test Workflow

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest

        steps:
        - name: Setup Go
            uses: actions/setup-go@v1
            with:
                go-version: 1.14
            id: go

        - name: Checkout
            uses: actions/checkout@v2
        
        - name: Unit Testing
            run: go test simulator

        - name: Build
            run: go build simulator.go